name: Compressed Size

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          version: 16.x

      - uses: pnpm/action-setup@v2
        with:
          version: 8.2.0

      - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
